ToDo/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('account/', include('account.urls')),
    path('taches/', include('taches.urls')),
    path('admin/', admin.site.urls),
]

account/urls.py
from django.urls import path

from .views import create_user, login_user, logout_view

app_name = 'account'

urlpatterns = [
    path('creation/', create_user, name='create'),
    path('login/', login_user, name='login'),
    path('logout/', logout_view, name='logout'),
]

taches/urls.py
from django.urls import path 
from .views import Home , TacheCreateViewt , TacheDetailView , TacheListView , TacheDeleteView,TacheUpdateView,CategorieCreateView,CategorieDeleteView,CategorieListView






urlpatterns = [
    path('categorie/',CategorieListView.as_view(),name='categorie_list'),
    path('categorie_edit/<int:pk>/',CategorieDeleteView.as_view(),name='categorie_delete'),
    path('categorie_form/',CategorieCreateView.as_view(),name='categorie_form'),
    path('tache_edit/<int:pk>/',TacheUpdateView.as_view(),name='tache_edit'),
    path('tache_delete/<int:pk>/',TacheDeleteView.as_view(),name='tache_delete'),
    path('tache_form/',TacheCreateViewt.as_view(),name='tache_form'),
    path('tache_detail/<int:pk>/',TacheDetailView.as_view(),name='tache_detail'),
    path('tache/',TacheListView.as_view(),name='tache_list'),
    path('',Home,name='home' ),

]

account/models.py
from django.db import models

# Create your models here.

taches/models.py
from django.db import models
from django.contrib.auth.models import User


class Taches(models.Model):
    PRIORITE_CHOICES = [
        (1, 'Haute'),
        (2, 'Moyenne'),
        (3, 'Basse'),
    ]
    titre = models.CharField(max_length=100)
    description = models.TextField()
    date_echeance = models.DateTimeField()
    priorite = models.IntegerField(choices=PRIORITE_CHOICES)
    status = models.BooleanField(default=False)
    categorie = models.ForeignKey('Categorie',on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=False)
 
class Categorie(models.Model):
    type = models.CharField(max_length=100,unique=True)

    def __str__(self):
        return self.type

account/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')
        widgets = {
                'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Votre nom'}),
                'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Votre prenom'}),
                'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Votre nom_utilisateur'}),
                'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Votre adresse email'}),
                'password': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'votre mot de passe'}),
            }


class UserLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Votre nom_utilisateur'}),)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control','placeholder' : 'votre mot de passe',}), min_length=8 )

taches/forms.py
from django import forms
from .models import Taches , Categorie


class TacheForm(forms.ModelForm) :

    class Meta :
        model = Taches
        fields = ('titre','description','date_echeance','priorite','categorie','status')
        widgets = {
            'titre' : forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Titre'}),
            'description' : forms.TextInput(attrs={'class': 'form-control', 'placeholder':'resume'}),
            'date_echeance' : forms.DateTimeInput(attrs={'class': 'form-control', 'placeholder':'Date de publication','type': 'datetime-local'}),
            'priorite' : forms.Select(attrs={'class' : 'form-control', 'placeholder':'priorite'}),
            'categorie': forms.Select(attrs={'class' : 'form-control', 'placeholder':'categorie de la tache'}),
        }

class CategorieForm(forms.ModelForm):
    class Meta:
        model = Categorie
        fields = ('type',)

account/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import redirect


from .forms import UserForm, UserLoginForm


def create_user(request):
    if request.user.is_authenticated:
        return redirect('tache_list')
    if request.method == 'GET':
        form = UserForm()
    elif request.method == 'POST':
        form = UserForm(data=request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            user = User.objects.create_user(
                username=cleaned_data.get('username'),
                email=cleaned_data.get('email'),
                password=cleaned_data.get('password')
            )
            user.first_name = cleaned_data.get('first_name')
            user.last_name = cleaned_data.get('last_name')
            user.save()
            return redirect('tache_list')
    data = {
        'form': form
    }
    return render(
        context=data, request=request, template_name='account/create.html'
        )


def login_user(request):
    if request.user.is_authenticated:
        return redirect('tache_list')
    if request.method == "GET":
        form = UserLoginForm()
    elif request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(
                request=request, username=username, password=password
                )
            if user is not None:
                login(request=request, user=user)
                return redirect('tache_list')

    context = {
        'form': form
    }
    return render(request, 'account/login.html', context)


def logout_view(request):
    logout(request)
    return redirect('home')

taches/views.py
from django.shortcuts import render , redirect , get_object_or_404 , HttpResponse
from django.urls import reverse , reverse_lazy
from django.views.generic import ListView , DetailView , CreateView , DeleteView , UpdateView
from .models import Taches , Categorie
from .forms import TacheForm , CategorieForm
from django.contrib.auth.mixins import LoginRequiredMixin




def Home(request):
    return render(request,'taches/home.html')

class TacheListView(ListView):
    model = Taches
    template_name = 'taches/tache_list.html'
    context_object_name = 'taches'

    def get_queryset(self):
        queryset = super().get_queryset()  # Obtenir le queryset de base

        # Filtrage par date d'échéance
        date_filtre = self.request.GET.get('date')
        if date_filtre:
            queryset = queryset.filter(date_echeance__date=date_filtre)

        # Filtrage par priorité
        priorite_filtre = self.request.GET.get('priorite')
        if priorite_filtre:
            queryset = queryset.filter(priorite=priorite_filtre)

        # Filtrage par catégorie (type de la catégorie)
        categorie_filtre = self.request.GET.get('q')  # Récupérer le terme de recherche de catégorie
        if categorie_filtre:
            # Utiliser la notation double underscore pour accéder au champ "type" de la catégorie associée
            queryset = queryset.filter(categorie__type__icontains=categorie_filtre)

        return queryset

class TacheCreateViewt(LoginRequiredMixin,CreateView):
    model = Taches
    form_class = TacheForm
    template_name = 'taches/tache_form.html'
    success_url = reverse_lazy('tache_list')

class TacheDetailView(DetailView):
    model = Taches
    template_name = 'taches/tache_detail.html'
    context_object_name = 'tache'

class TacheDeleteView(LoginRequiredMixin,DeleteView):
    model = Taches
    template_name = 'taches/tache_delete.html'
    success_url = reverse_lazy('tache_list')

class TacheUpdateView(LoginRequiredMixin,UpdateView):
    model = Taches
    form_class = TacheForm
    template_name = ('taches/tache_edit.html')
    success_url = reverse_lazy('tache_list')

class CategorieListView(ListView):
    model = Categorie
    template_name = 'taches/categorie_list.html'
    context_object_name = 'categories'
     

class CategorieCreateView(CreateView):
    model = Categorie
    form_class = CategorieForm
    template_name = 'taches/categorie_form.html'
    success_url = reverse_lazy('categorie_list')

class CategorieDeleteView(DeleteView):
    model = Categorie
    template_name = 'taches/categorie_delete.html'
    success_url = reverse_lazy('categorie_list')

taches/templates/taches/Layout.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>SEO Master - SEO Agency Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="keywords" />
    <meta content="" name="description" />

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon" />

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="" />
    <link
      href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500&amp;family=Roboto:wght@400;500;700&amp;display=swap"
      rel="stylesheet"
    />

    <!-- Icon Font Stylesheet -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
      rel="stylesheet"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
      rel="stylesheet"
    />

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet" />
    <link
      href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'lib/lightbox/css/lightbox.min.css' %}"
      rel="stylesheet"
    />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  </head>

  <body>
    <div class="container-xxl bg-white p-0">
      <!-- Spinner Start -->
      <div
        id="spinner"
        class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center"
      >
        <div
          class="spinner-grow text-primary"
          style="width: 3rem; height: 3rem;"
          role="status"
        >
          <span class="sr-only">Loading...</span>
        </div>
      </div>
      <!-- Spinner End -->

      <!-- Navbar & Hero Start -->
      <div class="container-xxl position-relative p-0">
        <nav
          class="navbar navbar-expand-lg navbar-light px-4 px-lg-5 py-3 py-lg-0"
        >
          <a href="" class="navbar-brand p-0">
            <h1 class="m-0">
              <i class="fa fa-search me-2"></i>1000<span class="fs-5"
                >TECHLEADERS</span
              >
            </h1>
            <!-- <img src="img/logo.png" alt="Logo"> -->
          </a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarCollapse"
          >
            <span class="fa fa-bars"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0">
              <a href="{% url 'home' %}" class="nav-item nav-link active">Home</a>
                {% if user.is_authenticated %}
                    <a href="{% url 'tache_list' %}" class="nav-item nav-link active">Mes Tâches</a>
                    <a href="{% url 'tache_form' %}" class="nav-item nav-link">Ajouter une Tâche</a>
                    <a href="{% url 'account:logout' %}" class="nav-item nav-link">Deconnexion</a>
                    <a href="{% url 'categorie_list' %}" class="nav-item nav-link">categorie</a>
                {% else %}
                    <a href="{% url 'account:login' %}" class="nav-item nav-link">Se Connecter</a>
                {% endif %}
            </div>
            
        </div>
        </nav>

      </div>
    

            {% block content %} {% endblock %}

   <!-- Footer Start -->
   <div
   class="container-fluid bg-primary text-light footer mt-5 pt-5 wow fadeIn"
   data-wow-delay="0.1s"
 >
   <div class="container py-5 px-lg-5">
     <div class="row g-5">
       <div class="col-md-12 col-lg-12">
           <div class="row">
               <div class="col-lg-3">
                   <p>
                       <i class="fa fa-map-marker-alt me-3"></i>123 Street, New York,
                       USA
                     </p>
               </div>
               <div class="col-lg-3">
                   <p><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>

               </div>
               <div class="col-lg-3">
                   <p><i class="fa fa-envelope me-3"></i>info@example.com</p>

               </div>
               <div class="col-lg-3">
                   <div class="d-flex" style="margin-top: -10px;">
                       <a class="btn btn-outline-light btn-social" href=""
                         ><i class="fab fa-twitter"></i
                       ></a>
                       <a class="btn btn-outline-light btn-social" href=""
                         ><i class="fab fa-facebook-f"></i
                       ></a>
                       <a class="btn btn-outline-light btn-social" href=""
                         ><i class="fab fa-youtube"></i
                       ></a>
                       <a class="btn btn-outline-light btn-social" href=""
                         ><i class="fab fa-instagram"></i
                       ></a>
                       <a class="btn btn-outline-light btn-social" href=""
                         ><i class="fab fa-linkedin-in"></i
                       ></a>
                     </div>
               </div>
           </div>
         
         
       </div>
      
 <!-- Footer End -->

 <!-- Back to Top -->
 <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top pt-2"
   ><i class="bi bi-arrow-up"></i
 ></a>
</div>

<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'lib/wow/wow.min.js' %}"></script>
<script src="{% static 'lib/easing/easing.min.js' %}"></script>
<script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'lib/isotope/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'lib/lightbox/js/lightbox.min.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

taches/templates/taches/categorie_delete.html
{% extends "taches/Layout.html" %}
{% load static %}
{% block content %} 
<div class="container-xxl py-5 bg-primary hero-header mb-5">
    <div class="container my-5 py-5 px-lg-5">
      <div class="row g-5 py-5">
        <div class="col-lg-6 text-center text-lg-start">
                            <div class="card mb-4">
                                <h1>Êtes-vous sûr de vouloir supprimer la categorie : "{{ categorie.type}}" ?</h1>
                                <form action="" method="post">
                                    {% csrf_token %}
                                    <input type="submit" value="Supprimer" class="btn btn-danger"  class="text-center " style="background-color: red;">
                                    <a href="{% url 'categorie_list' %}" class="btn btn-secondary">Annuler</a  class="text-center">
                                </form>
                            </div>
        </div>
        <div class="col-lg-6 text-center text-lg-start">
          <img
            class="img-fluid"
            src="{% static 'img/hero.png' %}"
            alt=""
          />
        </div>
      </div>
    </div>
  </div>
</div>
 {% endblock %}

taches/templates/taches/home.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>SEO Master - SEO Agency Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="keywords" />
    <meta content="" name="description" />

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon" />

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="" />
    <link
      href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500&amp;family=Roboto:wght@400;500;700&amp;display=swap"
      rel="stylesheet"
    />

    <!-- Icon Font Stylesheet -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
      rel="stylesheet"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
      rel="stylesheet"
    />

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet" />
    <link
      href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'lib/lightbox/css/lightbox.min.css' %}"
      rel="stylesheet"
    />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  </head>

  <body>
    <div class="container-xxl bg-white p-0">
      <!-- Spinner Start -->
      <div
        id="spinner"
        class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center"
      >
        <div
          class="spinner-grow text-primary"
          style="width: 3rem; height: 3rem;"
          role="status"
        >
          <span class="sr-only">Loading...</span>
        </div>
      </div>
      <!-- Spinner End -->

      <!-- Navbar & Hero Start -->
      <div class="container-xxl position-relative p-0">
        <nav
          class="navbar navbar-expand-lg navbar-light px-4 px-lg-5 py-3 py-lg-0"
        >
          <a href="" class="navbar-brand p-0">
            <h1 class="m-0">
              <i class="fa fa-search me-2"></i>1000<span class="fs-5"
                >TECHLEADERS</span
              >
            </h1>
            <!-- <img src="img/logo.png" alt="Logo"> -->
          </a>
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarCollapse"
          >
            <span class="fa fa-bars"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0">
              <a href="{% url 'home' %}" class="nav-item nav-link active">Home</a>
                {% if user.is_authenticated %}
                    <a href="{% url 'tache_list' %}" class="nav-item nav-link active">Mes Tâches</a>
                    <a href="{% url 'tache_form' %}" class="nav-item nav-link">Ajouter une Tâche</a>
                    <a href="{% url 'account:logout' %}" class="nav-item nav-link">Deconnexion</a>
                    <a href="{% url 'categorie_list' %}" class="nav-item nav-link">categorie</a>
                {% else %}
                    <a href="{% url 'account:login' %}" class="nav-item nav-link">Se Connecter</a>
                {% endif %}
            </div>
            
        </div>
        </nav>

        <div class="container-xxl py-5 bg-primary hero-header mb-5">
          <div class="container my-5 py-5 px-lg-5">
            <div class="row g-5 py-5">
              <div class="col-lg-6 text-center text-lg-start">
                <h1 class="text-white mb-4 animated zoomIn">
                    Bienvenue sur To-Do List, votre application web dédiée à la gestion de tâches quotidienne
                </h1>
                <p class="text-white pb-3 animated zoomIn">
                    Que vous soyez étudiant, professionnel ou simplement en quête d'une meilleure organisation personnelle, To-Do List vous offre une interface intuitive et des fonctionnalités robustes pour vous aider à atteindre vos objectifs.
                </p>
               
              </div>
              <div class="col-lg-6 text-center text-lg-start">
                <img
                  class="img-fluid"
                  src="{% static 'img/hero.png' %}"
                  alt=""
                />
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Navbar & Hero End -->

      <!-- Full Screen Search Start -->
      <div class="modal fade" id="searchModal" tabindex="-1">
        <div class="modal-dialog modal-fullscreen">
          <div class="modal-content" style="background: rgba(29, 29, 39, 0.7);">
            <div class="modal-header border-0">
              <button
                type="button"
                class="btn bg-white btn-close"
                data-bs-dismiss="modal"
                aria-label="Close"
              ></button>
            </div>
            <div
              class="modal-body d-flex align-items-center justify-content-center"
            >
              <div class="input-group" style="max-width: 600px;">
                <input
                  type="text"
                  class="form-control bg-transparent border-light p-3"
                  placeholder="Type search keyword"
                />
                <button class="btn btn-light px-4">
                  <i class="bi bi-search"></i>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Full Screen Search End -->

      <!-- About Start -->
      <div class="container-xxl py-5">
        <div class="container px-lg-5">
          <div class="row g-5">
            <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.1s">
              <div class="section-title position-relative mb-4 pb-2">
                <h6 class="position-relative text-primary ps-4">About Us</h6>
                <h2 class="mt-2">
                    To-Do List vous offre une interface intuitive et des fonctionnalités robustes pour vous aider à atteindre vos objectifs.
                </h2>
              </div>
              <p class="mb-4">
                Grâce à une interface épurée et facile à utiliser, vous pouvez classer vos tâches par priorité, les regrouper par catégories, et recevoir des rappels pour ne jamais manquer une échéance importante. Connectez-vous dès aujourd'hui pour commencer à optimiser votre productivité et prendre le contrôle de votre quotidien.
              </p>
              <div class="row g-3">
                <div class="col-sm-6">
                  <h6 class="mb-3">
                    <i class="fa fa-check text-primary me-2"></i>Etudiant
                  </h6>
                  <h6 class="mb-0">
                    <i class="fa fa-check text-primary me-2"></i>professionnel
                  </h6>
                </div>
                <div class="col-sm-6">
                  <h6 class="mb-3">
                    <i class="fa fa-check text-primary me-2"></i>24/7 Support
                  </h6>
                  <h6 class="mb-0">
                    <i class="fa fa-check text-primary me-2"></i>Fair Prices
                  </h6>
                </div>
              </div>
              <div class="d-flex align-items-center mt-4">
                <a class="btn btn-primary rounded-pill px-4 me-3" href=""
                  >Read More</a
                >
                <a class="btn btn-outline-primary btn-square me-3" href=""
                  ><i class="fab fa-facebook-f"></i
                ></a>
                <a class="btn btn-outline-primary btn-square me-3" href=""
                  ><i class="fab fa-twitter"></i
                ></a>
                <a class="btn btn-outline-primary btn-square me-3" href=""
                  ><i class="fab fa-instagram"></i
                ></a>
                <a class="btn btn-outline-primary btn-square" href=""
                  ><i class="fab fa-linkedin-in"></i
                ></a>
              </div>
            </div>
            <div class="col-lg-6">
              <img
                class="img-fluid wow zoomIn"
                data-wow-delay="0.5s"
                src="{% static 'img/about.jpg' %}"
              />
            </div>
          </div>
        </div>
      </div>
      <!-- About End -->

      

      

      <!-- Footer Start -->
      <div
        class="container-fluid bg-primary text-light footer mt-5 pt-5 wow fadeIn"
        data-wow-delay="0.1s"
      >
        <div class="container py-5 px-lg-5">
          <div class="row g-5">
            <div class="col-md-12 col-lg-12">
                <div class="row">
                    <div class="col-lg-3">
                        <p>
                            <i class="fa fa-map-marker-alt me-3"></i>123 Street, New York,
                            USA
                          </p>
                    </div>
                    <div class="col-lg-3">
                        <p><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>

                    </div>
                    <div class="col-lg-3">
                        <p><i class="fa fa-envelope me-3"></i>info@example.com</p>

                    </div>
                    <div class="col-lg-3">
                        <div class="d-flex" style="margin-top: -10px;">
                            <a class="btn btn-outline-light btn-social" href=""
                              ><i class="fab fa-twitter"></i
                            ></a>
                            <a class="btn btn-outline-light btn-social" href=""
                              ><i class="fab fa-facebook-f"></i
                            ></a>
                            <a class="btn btn-outline-light btn-social" href=""
                              ><i class="fab fa-youtube"></i
                            ></a>
                            <a class="btn btn-outline-light btn-social" href=""
                              ><i class="fab fa-instagram"></i
                            ></a>
                            <a class="btn btn-outline-light btn-social" href=""
                              ><i class="fab fa-linkedin-in"></i
                            ></a>
                          </div>
                    </div>
                </div>
              
              
            </div>
           
      <!-- Footer End -->

      <!-- Back to Top -->
      <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top pt-2"
        ><i class="bi bi-arrow-up"></i
      ></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/isotope/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'lib/lightbox/js/lightbox.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

taches/templates/taches/tache_list.html
{% extends "taches/Layout.html" %}
{% block content %} 
        <!-- Formulaire de filtrage -->
         
            <div class="container-xxl py-5 hero-header mb-5" style="background-color: #000080;">
                <div class="container my-5 py-5 px-lg-5">
                    <form class="d-flex mb-4" role="search" method="GET" action="">
                        <input class="form-control me-2" type="date" name="date" placeholder="Filtrer par date" value="{{ request.GET.date }}">
                        
                        <select class="form-control me-2" name="priorite">
                            <option value="">Toutes les priorités</option>
                            {% for value, label in taches.model.PRIORITE_CHOICES %}
                                <option value="{{ value }}" {% if request.GET.priorite == value|stringformat:"s" %}selected{% endif %}>{{ label }}</option>
                            {% endfor %}
                        </select>
                        
                        <input class="form-control me-2" type="search" name="q" placeholder="Rechercher par catégorie" value="{{ request.GET.q }}">
                        
                        <button class="btn btn-outline-success" type="submit">Filtrer</button>
                    </form>

                    <!-- Affichage des tâches sous forme de liste -->
                    <table class="table" style="background-color: white;">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Titre</th>
                                <th>Date d'échéance</th>
                                <th>Priorité</th>
                                <th>Catégorie</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for tache in taches %}
                            <tr>
                                <td>{{ tache.id }}</td>
                                <td>{{ tache.titre }}</td>
                                <td>{{ tache.date_echeance|date:"d/m/Y H:i" }}</td>
                                <td>{{ tache.get_priorite_display }}</td>
                                <td>{{ tache.categorie.type }}</td>
                                <td>{% if tache.status %}Complétée{% else %}Non complétée{% endif %}</td>
                                <td>
                                    <a href="{% url 'tache_detail' tache.id %}" class="btn btn-success">Details</a>
                                    <a href="{% url 'tache_edit' tache.id %}" class="btn btn-primary">Modifier</a>
                                  
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan="6">Aucune tâche trouvée.</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>


        </div>
         

{% endblock %}